export const works = [
  {
    id: 1,
    title: "Neon Genesis",
    author: "Crypto Artisan",
    image: "/cyberpunk-neon-art.jpg",
    images: ["/cyberpunk-neon-art.jpg", "/abstract-fabric-pattern.png", "/holographic-glass-sculpture.jpg"],
    story: "A vision of a future where neon lights replace the stars, guiding lost souls through the digital ether.",
    material: "Digital, Light, Code",
    likes: 124,
    tags: ["digital", "cyberpunk"],
    remixCount: 12,
    remixers: ["Alice", "Bob", "Charlie", "Dave"],
    collectionStatus: "none", // none, pending, approved, rejected
    savedAt: "2024-05-15 14:30",
  },
  {
    id: 2,
    title: "Ethereal Pottery",
    author: "Elena Crafts",
    image: "/ceramic-pottery-artistic.jpg",
    images: ["/ceramic-pottery-artistic.jpg", "/organic-wood-carving.jpg"],
    story: "Molded from the earth of the ancient riverbeds, fired in kilns whispering with old spirits.",
    material: "Clay, Glaze, Fire",
    likes: 89,
    tags: ["ceramic", "minimalist"],
    remixCount: 5,
    remixers: ["Eve", "Frank"],
    collectionStatus: "none",
    savedAt: "2024-06-20 09:15",
  },
  {
    id: 3,
    title: "Quantum Weave",
    author: "Textile Dreams",
    image: "/abstract-fabric-pattern.png",
    images: ["/abstract-fabric-pattern.png", "/glitch-art-tapestry.jpg"],
    story: "Threads that bind the fabric of reality, interwoven with quantum entanglements.",
    material: "Silk, Nanofiber",
    likes: 256,
    tags: ["fabric", "pattern"],
    remixCount: 34,
    remixers: ["Grace", "Heidi", "Ivan", "Judy", "Mallory"],
    collectionStatus: "approved",
    savedAt: "2024-07-01 18:45",
  },
  {
    id: 4,
    title: "Holographic Glass",
    author: "Glass Master",
    image: "/holographic-glass-sculpture.jpg",
    images: ["/holographic-glass-sculpture.jpg"],
    story: "Reflecting light from dimensions unseen.",
    material: "Glass, Hologram",
    likes: 45,
    tags: ["glass", "modern"],
    remixCount: 2,
    remixers: ["Niaj", "Olivia"],
    collectionStatus: "pending",
    savedAt: "2024-08-10 11:20",
  },
  {
    id: 5,
    title: "Cyber Metal",
    author: "Iron Age",
    image: "/futuristic-metal-sculpture.jpg",
    images: ["/futuristic-metal-sculpture.jpg"],
    story: "Forged in the heart of a dying star.",
    material: "Steel, Neon",
    likes: 112,
    tags: ["metal", "abstract"],
    remixCount: 8,
    remixers: ["Peggy", "Rupert"],
    collectionStatus: "rejected",
    savedAt: "2024-09-05 16:00",
  },
  {
    id: 6,
    title: "Neural Woodwork",
    author: "Bio Carver",
    image: "/organic-wood-carving.jpg",
    images: ["/organic-wood-carving.jpg"],
    story: "Wood that remembers the forest it came from.",
    material: "Oak, Varnish",
    likes: 67,
    tags: ["wood", "bio-design"],
    remixCount: 15,
    remixers: ["Sybil", "Ted", "Walter"],
    collectionStatus: "none",
    savedAt: "2024-10-12 10:30",
  },
  {
    id: 7,
    title: "Glitch Tapestry",
    author: "Pixel Weaver",
    image: "/glitch-art-tapestry.jpg",
    images: ["/glitch-art-tapestry.jpg"],
    story: "When the loom encounters a system error.",
    material: "Wool, Pixels",
    likes: 198,
    tags: ["textile", "glitch"],
    remixCount: 22,
    remixers: ["Zoe", "Yvonne"],
    collectionStatus: "none",
    savedAt: "2024-11-01 13:45",
  },
  {
    id: 8,
    title: "Void Sculpture",
    author: "Dark Matter",
    image: "/black-abstract-sculpture.jpg",
    images: ["/black-abstract-sculpture.jpg"],
    story: "Giving form to the nothingness.",
    material: "Vantablack, Resin",
    likes: 342,
    tags: ["sculpture", "void"],
    remixCount: 45,
    remixers: ["Xavier", "William", "Victor"],
    collectionStatus: "none",
    savedAt: "2024-11-20 09:00",
  },
]
